### ISSUE TITLE
Experiment with source code formatter

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#117]
[Brittany](https://github.com/lspitzner/brittany) might work, we can fork it if necessary.

@mariari has strong preferences.

**Comment by cwgoes** [comment]
... we should formalize style guidelines so that we don't have PRs like https://github.com/cryptiumlabs/juvix/pull/128.

Specifically, we should:
- Add whatever autoformatters and linters we want to CI
- Avoid changing anything else, code is considered "correctly styled" modulo whatever the CI accepts
- If style changes are desired, they must come with CI changes attached

**Comment by mariari** [comment]
Investigating [ORMOLU](https://www.tweag.io/posts/2019-05-27-ormolu.html) for the code formatter

**Comment by mariari** [comment]
Seems like Ormolu currently has issues running

```bash
┌─[katyusha@navi]─[~/Documents/Work/Repo/juvix/src/Juvix/Bohm]
└──╼ ~/.local/bin/ormolu Translation.hs --ghc-opt DerivingVia --ghc-opt UnicodeSyntax
```
gives me

```bash
Parsing of source code failed:
  Translation.hs:62:9-55
  Parse error in pattern: (Just portInfo, _)
                          → chaseAndCreateFan portInfo
```
what a shame. By default it enables the unicode extension yet it fails here for some reason.

**Comment by cwgoes** [comment]
If disabling `-XUnicodeSyntax` allows the autoformatter to work, I think that's worth it.

**Comment by cwgoes** [comment]
It seems to incorrectly remove spaces in type applications though.

**Comment by cwgoes** [comment]
Maybe we should fork it, fix all the issues, and submit an upstream PR.

**Comment by cwgoes** [comment]
Also, I don't like the newline between function signatures & definitions.

**Comment by cwgoes** [comment]
Working on a fork: https://github.com/cryptiumlabs/ormolu

**Comment by cwgoes** [comment]
Fixed the parser issues & added Unicode output in the fork.
