### ISSUE TITLE
Investigate type systems that are more user-friendly

### ISSUE THREAD

**Issue by thealmarty** [cryptiumlabs/juvix#14]
Related to #3 
Reduce the need to prove obvious facts: 

- [ ] [Type-Theory In Color](https://dl.acm.org/citation.cfm?id=2500577) ([Research Gate Copy](https://www.researchgate.net/publication/266654430_Type-Theory_in_Color))

**Comment by cwgoes** [comment]
[Catalog of language UX inspirations](https://futureofcoding.org/catalog/).

**Comment by cwgoes** [comment]
[Excellent essay / overview of "tools for thought"](https://numinous.productions/ttft/print/TTFT.pdf).

**Comment by cwgoes** [comment]
This may be a duplicate of https://github.com/cryptiumlabs/juvix/issues/3, should we consolidate it?

**Comment by thealmarty** [comment]
Consolidated to #124 .
