### ISSUE TITLE
Updates to BOHM interpreter

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#158]
After https://github.com/cryptiumlabs/juvix/pull/145 is merged, I suggest we:
- [x] Rename BOHM to `INet` or something like that, since it isn't actually BOHM (no oracle)
- [x] Parameterise BOHM over `primTy` / `primVal` in a manner compatible with Core
- [ ] ~Remove unused primitives (these should be replaced by parameterised primitives)~
- [x] Ensure that erased (elementary affine) core can be fully converted/evaluated in the inet
- [ ] Ensure the conversion logic for curried functions matches what we will use for LLVM
  (hopefully this will make the LLVM backend easier to debug)

I can probably do these but wanted to check with you first @mariari.

Any other changes/features you think would be prudent for the interaction net interpreter?

**Comment by mariari** [comment]
Seems fine, might take a little bit of work.

I don't think much else needs to be changed outside of updating the parser as well

**Comment by cwgoes** [comment]
Is it worth parsing BOHM separately?

Probably, but only if we have special node types which are converted from core...

**Comment by cwgoes** [comment]
For example, it would probably be wise to test the bespoke encoding path in the interpreter.

**Comment by cwgoes** [comment]
Perhaps we should leave some custom nodes in the AST, to match what we end up specialising in the interaction net compilation pipeline (e.g. for LLVM).

For now I'm just adding the primitive type/value parameterisation.
