### ISSUE TITLE
Update layout.org with new code layout

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#176]
Michelson backend, interaction net interpreter, LLVM (when complete).

**Comment by cwgoes** [comment]
If we end up using [Haddock](https://www.haskell.org/haddock/), do you think this file is helpful in addition, or would it be redundant?

**Comment by mariari** [comment]
I think the file would still be useful, due to having information that wouldn't necessarily fit with the haddock. 

An alternative approach would be to just scrape the Haddock documentation, generate the file and the dependencies, for a more brief look at what each file does and what it depends on

**Comment by cwgoes** [comment]
Concluded:
- Autogenerate from top module comments
- Colloquial comments are OK
- Convert format as necessary

**Comment by cwgoes** [comment]
Done by @mariari in #188 et al. Over time we should add comments to all source files.
