### ISSUE TITLE
Clean up the erasure, general type/usage pass-through compilation stack

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#190]
Follow-up to https://github.com/cryptiumlabs/juvix/pull/180

- Avoid calling typechecker in erasure
- Figure out best way to pass through info on types, usages of subterms

**Comment by cwgoes** [comment]
- [ ] Type/usage annotated version of core (for erasure)
- [ ] Type/usage annotated version of erased core (for backends)

**Comment by cwgoes** [comment]
I started altering the typechecker to return annotated core but stopped midway - wanted to consult with @thealmarty first - it's pretty messy with the HOAS values if `typeTerm` / `typeElim` return annotations instead of values. Maybe there's a cleaner way.

**Comment by thealmarty** [comment]
I agree that it's pretty messy. I propose the following options:

1. don't worry about the type checker being called again in `Erasure` - it's overkill to do so much code repetition to avoid running the type checker more than once. It adds other inefficiency and the type checker isn't heavy.

2. type check first then erase in the same function. So we'd have a function similar to [this](https://github.com/cryptiumlabs/juvix/blob/e2f88db44a5efc348746b7c5cf9fde812d7cec2a/src/Juvix/Core/Pipeline.hs#L52) but altered such that the type checker results will pass through without repetition.

Option 1 is easy cause it was already done. Were there other downsides to it? Option 2 should be doable. Thoughts?

**Comment by cwgoes** [comment]
It's not so much the performance that concerns me with (1) but rather that it makes the erasure logic more complex (e.g. it has to track the environment to call the type-checker).

In *either* case we need to pass type & usage information down to the various backends, since they will need it, so I don't think we can avoid some changes to the type-checker to return sub-type information. Given that I am sceptical that (2) is really helpful - I don't think we can combine type-checking, erasure, and backend compilation all in one function without way too much complexity.

**Comment by cwgoes** [comment]
A few things we could do to simplify:
- Move value application (`vapp`, `cEval`, `iEval`) to a separate file, since it is independent from typechecking (used by typechecking, but it doesn't use the typechecker itself)
- Either switch away from HOAS (I think this might be easiest) or at least use only HOAS and not HOAS *and* index-bound variables (ref https://github.com/cryptiumlabs/juvix/pull/203#discussion_r351128599)
- Put the error strings in a `Show` typeclass instances (#174 does this already)

**Comment by cwgoes** [comment]
I'll try to update the Michelson backend using the annotated IR and make sure it works. Once it does and we know exactly what annotations are required we can figure out how best to update the typechecker / erasure steps.

**Comment by cwgoes** [comment]
Subsumed by #333 and more recent issues.
