### ISSUE TITLE
Deal with omega / natural usage comparisions

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#191]
Right now we use an `Eq` instance, this is a bit confusing and might lead to mistakes.

I think comparing on an ordering might be better, and we should review where exactly in the typechecker we are doing this.

**Comment by thealmarty** [comment]
> Right now we use an `Eq` instance, this is a bit confusing and might lead to mistakes.
> 
> I think comparing on an ordering might be better, and we should review where exactly in the typechecker we are doing this.

As per the language reference, currently usages are exact, so `Eq` instance is required. Do we want to change the spec to *less than or equal to* usages? We can avoid using `Eq` instance then. That is:

0 usage implies no computational usage.
1 usage implies 1 or 0 computational usage.
n usage implies n or less computational uage.
w usage implies any number of usage (unchanged from current spec)

**Comment by thealmarty** [comment]
Actually that still wouldn't solve the issue that checking `== SNat 0` (see if a variable was zero-usage) returns true for Omega, because Omega is defined as any number of usage.

**Comment by cwgoes** [comment]
> Do we want to change the spec to less than or equal to usages?

I think we want exact usages, without weakening (especially with the upcoming first-class usage type theory upgrade) - but there will be some less-than-or-equal check somewhere for `w`, insofar as we are counting usages (since `w` just means 'any number of usages', and we can't ever use a variable `w` times).

Where do we use the `==` instance in the typechecker? It looks like:

[line 134](https://github.com/cryptiumlabs/juvix/blob/develop/src/Juvix/Core/IR/Typechecker.hs#L134)
[line 147](https://github.com/cryptiumlabs/juvix/blob/develop/src/Juvix/Core/IR/Typechecker.hs#L134)
[line 163](https://github.com/cryptiumlabs/juvix/blob/develop/src/Juvix/Core/IR/Typechecker.hs#L163)
[line 183](https://github.com/cryptiumlabs/juvix/blob/develop/src/Juvix/Core/IR/Typechecker.hs#L183)

In the first three cases, I think we do want to be checking that the usage is actually `0` (so the current logic is wrong - e.g. `* 0 : w * 1` is not a valid judgement, but it would be accepted). In the last case, equality might be OK, or we might allow `(x : w T) : 3 T` to be admitted, but I don't think the type theory does at the moment, so let's leave it out unless we decide that we need it later (note: that's *not* weakening, weakening would be to admit `(x : 3 T) : 2 T`, which I think we don't want.

Let's try changing it and see in detail what breaks, maybe test-cases need to be altered or some of the primitive logic needs to be special-cased differently.

> As per the language reference, currently usages are exact, so Eq instance is required.
> Actually that still wouldn't solve the issue that checking == SNat 0 (see if a variable was zero-usage) returns true for Omega, because Omega is defined as any number of usage.

I think we should have an `Eq` instance, but that it should actually check equality (so we can use `deriving (Eq)` as usual).

**Comment by thealmarty** [comment]
We need an Eq instance that is not symmetric. I.e., x == y /=> y == x.
When checking equality, 
_ == Omega but Omega /= _ because we want 

the result when we check if an annotation is `Omega`, the input usage being any `SNat` to return true.
(2) the result when we check if an annotation is 0 usage, the input usage being `Omega` to return `False`.

So we should get the desired behaviour if I change the [`Eq` instance](https://github.com/cryptiumlabs/juvix/blob/e88709e79d3cb51d61c7048115c712aa26a19bea/src/Juvix/Core/Usage.hs#L21) to
 
~~~~
instance Eq NatAndw where
  SNat x == SNat y = x == y
  Omega == _ = False
  SNat x == Omega = True
~~~~

See PR #196 . But a number of tests don't pass - all of them are not passing in the way that the expected and the got results are the same! To be investigated.

**Comment by cwgoes** [comment]
> (1) the result when we check if an annotation is Omega, the input usage being any SNat to return true.

I think we should do this with a `compare` instance, since it is not symmetric (whereas equality is usually symmetric, meaning that `x == y = y == x`)

**Comment by cwgoes** [comment]
edit: Never mind, a compare instance doesn't make sense, since we only want this for `w`. How about a function `exactOrMany` ?

**Comment by thealmarty** [comment]
I will write a custom function, `exactOrMany`, pattern matching all compare scenarios. The function captures the properties of `Omega` and `SNat` as per the language reference. The current `Eq` instance will be removed.

**Comment by thealmarty** [comment]
See PR #200.
