### ISSUE TITLE
Language reference updates for Isohypsibius

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#204]
- [x] Detail usages for primitive functions
- [x] More detailed inet reduction algorithm
- [x] Some details on Michelson backend compilation algorithm
- [x] Details / examples on induction for primitive types
- [x] More details on whole-program optimisation passes

**Comment by cwgoes** [comment]
- [ ] Details on primary pair tracking for reduction algorithms, safety of each-pair-once

**Comment by thealmarty** [comment]
maybe add the following to the list?
- [ ] Update/verify typing rules for `Prim-Const`, `Prim-Fn`, `App`. Remove `Prim-Fn-App` if not applicable.
- [ ] Add examples to each typing rule (can be taken from the core type checker tests that pass, e.g., the term `x` type checked with computational annotation ...and contemplation annotation ...)

**Comment by cwgoes** [comment]
> Remove Prim-Fn-App if not applicable.

Yes, it isn't necessary, I removed it.

**Comment by cwgoes** [comment]
Punting a few questions to post-release: https://github.com/cryptiumlabs/juvix/issues/253
