### ISSUE TITLE
Typechecker "debug mode"

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#209]
So that we can better understand the typechecking process for a term, and ensure that all steps match up with the type theory specified in the language reference (and that we understand where precisely they are being applied), I suggest that we implement a "debug mode" in the typechecker where we write a log entry each time a rule from the language reference is applied, and what variables were in scope at the time. This will probably require a writer monad of some sort. Then, if the user wants to examine the typing process, they can instruct Juvix to print out all these lots.

This will also be helpful for error message generation later on, I expect.

**Comment by thealmarty** [comment]
I was thinking the same. I'll get this going before writing more tests because this will help us with testing too.

**Comment by cwgoes** [comment]
Are there remaining tasks here? Separating logs into a datatype, perhaps?

**Comment by thealmarty** [comment]
> Are there remaining tasks here? Separating logs into a datatype, perhaps?

Yes. I'd like to do a bit more debugging first, then I'm ready to tidy it all up into a datatype.

**Comment by cwgoes** [comment]
@andy-morris We already have a basic debug mode, let's preserve it when we update the typechecker for first-class usages. I think we can go ahead & close this issue though.
