### ISSUE TITLE
Architectural choice documentation

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#214]
Where we make a non-obvious architectural choice that could have been made differently, we should document what & why in some canonical location for future reference & in order to maintain consistency across the codebase.

Examples:
- Usage of `capability` library (e.g. instead of `mtl`)
- de Bruijin indices in the typechecker (e.g. instead of names)
- Backend parameterisation (implied a bit by the language reference, but still)

We should also document if we intend to consider changing a decision in the future should other considerations prevail (e.g. performance for an effect system).

One format for this is an [Architectural Decision Record](https://adr.github.io/).

thoughts @thealmarty @mariari ?

**Comment by mariari** [comment]
Seems like a very good idea to document architectural decisions.

As per format, I think it's fine either way, if you think we should use an ADR, then we should go for it. Though I think even something as simple as a normal org or markdown file would work well enough.

One slight nitpick: 
- capability uses MTL, it just shadows functions revolving around the types

**Comment by cwgoes** [comment]
Maybe ADRs are overkill for now, we could start with a simple Markdown file and add more structure if we end up needing it later.

**Comment by cwgoes** [comment]
Documents for all items listed above have been added & will continue to be, this issue is not needed.
