### ISSUE TITLE
Make sure type checker behaves as desired

### ISSUE THREAD

**Issue by thealmarty** [cryptiumlabs/juvix#223]
See discussion on #203 regarding `depIdentity`'s annotation.

After #212  is done this can be investigated further.

Also, after #212  we should examine all the logs of the tests and make sure they all make sense.

**Comment by thealmarty** [comment]
The type checker currently doesn't check that sigma is 0 or 1 but the lang ref says sigma is 0 or 1 (see P.20) - I remember we had doubts about that. 

But I should either stick with the lang ref and check sigma is 0 or 1 or change the lang ref and not check that. Please advise @andy-morris and @cwgoes

**Comment by cwgoes** [comment]
> The type checker currently doesn't check that `sigma` is 0 or 1 but the lang ref says `sigma` is 0 or 1 (see P.20) - I remember we had doubts about that.
> 
> But I should either stick with the lang ref and make sure `sigma` is 0 or 1 or change the lang ref and leave the code as is. Please advise @andy-morris and @cwgoes

For now, in the current version, we should check that `sigma` is 0 or 1 in judgements.

**Comment by thealmarty** [comment]
I think the type checker is doing fine in terms of [these cases]( https://gist.github.com/thealmarty/c92f0dc76fec6a86abfa8d1aaacf924b) (see conclusion in the last paragraph).

**Comment by thealmarty** [comment]
I document the type checker behaviour [here](https://gist.github.com/thealmarty/c92f0dc76fec6a86abfa8d1aaacf924b) regarding how it type checks `depIdentity`. I think the type checker behaves as per the typing rule. @cwgoes and @andy-morris you can see what you think of the behaviour and let me know if you have any questions/comments.

**Comment by thealmarty** [comment]
> > The type checker currently doesn't check that `sigma` is 0 or 1 but the lang ref says `sigma` is 0 or 1 (see P.20) - I remember we had doubts about that.
> > But I should either stick with the lang ref and make sure `sigma` is 0 or 1 or change the lang ref and leave the code as is. Please advise @andy-morris and @cwgoes
> 
> For now, in the current version, we should check that `sigma` is 0 or 1 in judgements.

Typing rules to be updated to properly constrain `sigma` to 0 or 1. WIP #237

**Comment by thealmarty** [comment]
> I document the type checker behaviour [here](https://gist.github.com/thealmarty/c92f0dc76fec6a86abfa8d1aaacf924b) regarding how it type checks `depIdentity`. I think the type checker behaves as per the typing rule. @cwgoes and @andy-morris you can see what you think of the behaviour and let me know if you have any questions/comments.

Actually I'm not sure if it's ok for case 5 to type check - is it okay for the type checker to not enforce pi = 1 in this case?

**Comment by thealmarty** [comment]
To-Dos (feel free to add to this list):

[ ] should this `depIdentity` definition type checked? Is it correct that when the return is `Local 1` it does not type checked?
[ ] type checker doesn't seem to check `pi` for contemplating annotation?  See [here](https://gist.github.com/thealmarty/c92f0dc76fec6a86abfa8d1aaacf924b).

**Comment by thealmarty** [comment]
From the log below for the annotation of `(1, 0 * -> 1 Local 0 -> Local 1)` I need to make it so that the log shows more! It stopped where it's the most relevant i.e., where it fails! 

Progress 1/2: juvix\x. \x. Bound 0 : [1] Bound 1 should check as type (1,Right [Π] * 0-> [Π] Local 0-> Local 1): FAIL
  test/CoreTypechecker.hs:49:
  expected: Left Type mismatched. 
  Local 1 : [1] Local 0 
   (binder number 2) is of type 
  Right Local 0 , with 1 usage.
   But the expected type is Right Local 1 , with 1 usage.
   but got: Right ()

1 out of 1 tests failed (0.01s)
Type checking the term \x. \x. Bound 0 : [1] Bound 1against the input annotation with usage of 1, and type of Right [Π] * 0-> [Π] Local 0-> Local 1. \x. \x. Bound 0 : [1] Bound 1patterned matched to be a Lam term. Checking that input annotation has sigma usage and is of dependent function type (Pi).Check passed. Checking that M, with x (annotated with sig*pi usage) in the context, type checked against the input annotation.Type checking the term \x. Bound 0 : [1] Local 0against the input annotation with usage of 1, and type of Right [Π] Local 0-> Local 1. \x. Bound 0 : [1] Local 0patterned matched to be a Lam term. Checking that input annotation has sigma usage and is of dependent function type (Pi).Check passed. Checking that M, with x (annotated with sig*pi usage) in the context, type checked against the input annotation.Type checking the term Local 1 : [1] Local 0against the input annotation with usage of 1, and type of Right Local 1. Local 1 : [1] Local 0Type checking the term Local 1 : [1] Local 0, which patterned matched to be an Ann term. Checking that theTerm (M) has usage sigma and its type (S) is equivalent to the input type (T).Type checking the term Local 1against the input annotation with usage of 1, and type of Right Local 0. Local 1Type checking the term Local 1, which patterned matched to be a free variable. Looking up the free variable in the context [(Local 1,(1,Right Local 0)),(Local 0,(0,Right * 0))]Check passed. The variable is found in the context with annotation of usage 1and type Right Local 0Check passed. The type                   
juvix> Test suite juvix-test failed
Completed 2 action(s).
Test suite failure for package juvix-0.0.0.0
    juvix-test:  exited with: ExitFailure 1
Logs printed to console

**Comment by thealmarty** [comment]
> From the log below for the annotation of `(1, 0 * -> 1 Local 0 -> Local 1)` I need to make it so that the log shows more! It stopped where it's the most relevant i.e., where it fails!
> 
Done in #260

**Comment by cwgoes** [comment]
@thealmarty Can we close this? I believe we figured out the de-Bruijin index issue.

**Comment by thealmarty** [comment]
We can close this. Still need to check sigma = {0,1} in the type checker (see #237)
