### ISSUE TITLE
Trees that grow [extensible abstract syntax]

### ISSUE THREAD

**Issue by andy-morris** [cryptiumlabs/juvix#266]
I've been thinking about how to implement unification, as you know, and one of the things that will be necessary is adding metavariables to the syntax of core. However, we presumably won't want these floating around forever.

The simplest way to do this (other than just calling `error` or something when a metavariable shows up somewhere unexpected) is to just have two copies of the syntax. But this doesn't scale if we end up needing to add other temporary embellishments elsewhere. (Which... we already do, in `IRAnn`.)

So, I'm wondering if we might want to consider adapting the ideas from [Trees that Grow](http://www.jucs.org/jucs_23_1/trees_that_grow/jucs_23_01_0042_0062_najd.pdf):

```
-- in a class so they can be given defaults and
-- phases only need to override the ones they care about
class Anns ann where
  type XStar ann primVal primTy -- annotation for Star
  type XStar _ _ _ = ()
  type XPrimTy ann primVal primTy
  type XPrimTy _ _ _ = ()
  -- ...
  type XTerm ann primVal primTy -- extra forms
  type XTerm _ _ _ = Void
  -- likewise for Elim and (probably) Value & Neutral

type AllX (c :: Type -> Constraint) ann primTy primVal =
  (c (XStar ann primTy primVal), ...,
   c (XElim ann primTy primVal))

data Term ann primVal primTy
  = Star Natural (XStar ann primVal primTy)
  -- ...
  | XTerm (XTerm ann primVal primTy)

data Elim ann primVal primTy = ...
data Value ann primVal primTy m = ...


data NoAnn
instance Anns NoAnn

data Unifier
instance Anns Unifier where
  type XTerm Unifier _ _ = Metavar

data IRAnn
instance Anns IRAnn where
  type XLam IRAnn primVal primTy = Annotation IRAnn primVal primTy ann
  type XElim IRAnn primVal primTy = Annotation IRAnn primVal primTy
  type App IRAnn primVal primTy =
    (Annotation IRAnn primVal primTy, Annotation IRAnn primVal primTy)
```

Unfortunately, this approach isn't perfect:

- Deriving no longer works as is, iirc, so instead of `deriving Eq` you have to say

  ```
  deriving instance AllX Eq primTy primVal a => Eq (Term primTy primVal a)
  ```

- Compilation might get noticeably slower, from `AllX` expanding into twenty or so superclasses.

- Writing a traversal that works over all annotations is a little annoying, but I expect most functions will probably make sense for a specific `ann` anyway.

**Comment by thealmarty** [comment]
As per our meeting, @andy-morris will implement this and we'll discuss after.

**Comment by cwgoes** [comment]
> Deriving no longer works as is, iirc, so instead of deriving Eq you have to say
> Compilation might get noticeably slower, from AllX expanding into twenty or so superclasses.

These aren't a big deal I think (unless compilation gets *really* slow).

> Writing a traversal that works over all annotations is a little annoying, but I expect most functions will probably make sense for a specific ann anyway.

Can we combine annotations in some nice generic fashion?

Also, we will want typed transforms from "terms with annotations X" to "terms with annotations Y". That should be possible without too much trouble I think.

Generally I like this idea.

**Comment by cwgoes** [comment]
Also note that we will need mutually inductive definitions between primitive types / values and the core calculus, e.g.:

```haskell
data Term2 primTy primVal
  = Star2 Natural
  | Prim2 (primTy (Term2 primTy primVal))
  | Lam2 Symbol (Term2 primTy primVal)
  deriving (Generic)

data PrimTyEx term
  = PrimTy0
  | PrimPairT term term
  deriving (Generic)

type Term2Ex = Term2 PrimTyEx ()

test1 :: Term2Ex
test1 = Star2 0

test2 :: Term2Ex
test2 = Prim2 (PrimTy0)

test3 :: Term2Ex
test3 = Prim2 (PrimPairT (Star2 0) (Star2 1)) 
```

**Comment by andy-morris** [comment]
done in #299.
