### ISSUE TITLE
Michelson backend tasks

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#304]
- [x] Inline fully-applied functions (both primitives & user-defined)
- [x] Optimise stack logic for variables
- [x] Clean up the lambda compilation logic
- [ ] Figure out whether using type-based function arity is sufficient for the initial version
- [ ] Add `let` to IR

(later)

- [ ] Utilise usage information to avoid duplication
- [ ] Deal with datatypes

Also ref https://github.com/cryptiumlabs/juvix/issues/168.

**Comment by mariari** [comment]
Current issues with the Push/Enter and Constant Propagation
1. Fix argument order of how functions take arguments
    - Most likely we should evaluate arguments right to left pushing in that order.
      This way the arguments are in the proper order for primtives.
2. Consider how partial application deals with argument order
3. Depending on how we handle the above, either fix evaluation order or properly name the arguments to primtiive functions.
4. General debugging.
5. Remvoing all holes.
6. having `VStack.promote` call `funcToLambda` in the lambda promotion case

With these issues noted we can merge #305

**Comment by cwgoes** [comment]
Closing in favour of https://github.com/cryptiumlabs/juvix/issues/330.
