### ISSUE TITLE
Extra Work for the Michelson DSL.

### ISSUE THREAD

**Issue by mariari** [cryptiumlabs/juvix#324]
For issue #322 

1) Curried Application -> Lambda

2) Filling the undefined hole in

```haskell
addExpanded ∷ Env.Ops m ⇒ Protect → m ()
addExpanded (Protect (Env.Expanded _) i) = addInstrs i
addExpanded (Protect (Env.Constant v) _) = addInstr (Instructions.push undefined v)
addExpanded (Protect (Env.Curr {}) _) = undefined
```

  - The Curr case should just call 1)

Everything else I should be able to handle

**Comment by mariari** [comment]
Another Such function  that should hopefully already be done/easy that I will assign is

```haskell
typeToPrimType ∷ Types.Type → Untyped.Type
typeToPrimType = undefined
```
in InstructionsEff

**Comment by cwgoes** [comment]
Should I start on these now or wait for https://github.com/cryptiumlabs/juvix/pull/322 to be in a final state?

**Comment by mariari** [comment]
Feel free to start now

**Comment by mariari** [comment]
Another task would be filling in the following hole
```haskell
primToFargs ∷ Num b ⇒ Types.NewPrim → Types.Type → (Env.Fun, b)
primToFargs (Types.Constant (V.ValueLambda _lam)) _ty =
  (undefined, 1)
primToFargs (Types.Inst inst) ty =
  case inst of
    -- Can't abstract out pattern due to bad forall resolution!
    Instr.ADD _ → (Env.Fun (add ty), 2)
   ...
```

And changing the test examples

**Comment by cwgoes** [comment]
So, in the case of `primToFargs`, I am not actually sure we need to support `ValueLambda`; is there any reason we would ever compile to that? We do need to support arguments to contract calls which are themselves lambdas, but those wouldn't be `ValueLambda`s (they'll be some abstract arg).

**Comment by cwgoes** [comment]
@mariari Can you clarify what "Curried Application -> Lambda" refers to?

**Comment by cwgoes** [comment]
Also, it looks like we still need to update `Compilation/Term.hs` et al. to use the new DSL.

**Comment by mariari** [comment]
> @mariari Can you clarify what "Curried Application -> Lambda" refers to?

Sure, this means promoting a curried application/Juvix lambda into an actual lambda. We did this before at the top level if we didn't have enough arguments, or when say a function like Michelson `map` needs a lambda.

We wrote [a version in the old source code here](https://github.com/cryptiumlabs/juvix/blob/develop/src/Juvix/Backends/Michelson/Compilation/Lambda.hs#L68).

Once we have this up, we now have everything mudlo certain primititves to run Michelson

**Comment by mariari** [comment]
> Also, it looks like we still need to update `Compilation/Term.hs` et al. to use the new DSL.

That code  will be deleted, the DSL effectively replaces all the work in Compilation minus Types and VStack.

I find it odd how it took shape to basically do the job.

**Comment by cwgoes** [comment]
Subsumed by https://github.com/cryptiumlabs/juvix/pull/322#issuecomment-594605375.
