### ISSUE TITLE
Comments on proof UX research & proposal

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#327]
Commenting on HackMD documents does not seem to be possible (or I don't know how), so putting these here - once ready, I think it would be nice for both documents to be turned into PRs with Markdown files to be added to this repository, since those are a bit easier to review. Perhaps we can setup automatic rendering for all the docs like this on the Juvix website (ref https://github.com/cryptiumlabs/juvix/issues/286).

1st document: [Proof UX / editor experience](https://hackmd.io/@cyberglot/Sy48OTL7I)

> Language/Editor co-design aimed at (functional) programming education and interactive data science notebook à la IPython/Jupyter.

One aspect we'll really want to think about here is how the particularities of smart contract development & deployment inform the requirements of the editor experience. In particular, I think it will generally be preferable if the same tool can be used for development / prototyping / debugging *and* production deployment - that way the user doesn't have to switch tools & configs completely for production, which is annoying/risky - but if that's so we need to make sure that workflows for both prototyping (which prioritises quick deployment, debuggability, etc.) and production deployment (which prioritises safety, confirmation of all actions, etc.) exist within the same tool. In particular, this will likely mean that this editor must *connect* to development and/or live instances of blockchains (Tezos, at first), and be able to deploy contracts / read state / etc.

> It would be nice to have LF because I’ve seen Abella and Twelf in practice, but we would need to proposed our own LF-based semantics for smart contract proofs and at this point it seems like too much effort. We can, however, add logic programming features such as backtracking or integrate that with SMT.

Generally, I agree with this. Further LF features are probably "Juvix 2.0" material.

2nd document: [Juvix Proof UX proposal / editor integration](https://hackmd.io/@cyberglot/BkT2-DY78)

Agreed that a language server makes sense.

2/3/4 seem like they will be filled out more, so waiting to review those.

“Algebraic effects and handlers”-based experience - The example code makes sense, but I am not sure that I understand the theory yet - how does this differ from a tactics system? Is the difference just that intermediate results (`+_assoc`, `+_0_lrid`) are values and that the syntax is monadic, or is there a more fundamental difference?

**Comment by cyberglot** [comment]
> The example code makes sense, but I am not sure that I understand the theory yet - how does this differ from a tactics system?

Yes, it is basically a tactics system based on named delimited continuations, meaning we can add more tactics (or even effects like `Trace` or `PrettyPrint`) in a way they can compose with each other (or at least don't interfere). Part of this is an inspiration from Bob Atkey's paper on running a type system checker within a monad (can't find it right now, will edit when I do).

**Comment by mariari** [comment]
> > The example code makes sense, but I am not sure that I understand the theory yet - how does this differ from a tactics system?
> 
> Yes, it is basically a tactics system based on named delimited continuations, meaning we can add more tactics (or even effects like `Trace` or `PrettyPrint`) in a way they can compose with each other (or at least don't interfere). Part of this is an inspiration from Bob Atkey's paper on running a type system checker within a monad (can't find it right now, will edit when I do).

I wonder, Is this how F*'s tactic system works?

All effects in F* are ran in a particular monad (I forget the name of it), thus the tactic system is merely an effect in said system.

**Comment by cwgoes** [comment]
Closing in favour of https://github.com/cryptiumlabs/juvix/issues/338.
