### ISSUE TITLE
Should primitive types check against *any* ⋆ᵢ?

### ISSUE THREAD

**Issue by andy-morris** [cryptiumlabs/juvix#363]
Since we already allow `⋆ᵢ : ⋆ⱼ` for any `i ≤ j`, I think we should also allow e.g. `Nat: ⋆₁₀₀`, right? Currently the typechecker only allows `⋆₀` for primitive types.

**Comment by cwgoes** [comment]
Yes, that seems right.

**Comment by thealmarty** [comment]
Yes I agree. `Nat : ⋆n`, where n is any `nat`, should type check. Thanks for catching that.

**Comment by andy-morris** [comment]
fixed in #356
