### ISSUE TITLE
Upgrading to Haskell 8.8

### ISSUE THREAD

**Issue by mariari** [cryptiumlabs/juvix#365]
We will likely want to do this soon, namely because Ormolu does not compile with 8.6.

Another benefit of 8.8 is that we will be able to try out Brittney again (I'm not sure the issue with forall is present in 8.8).

Packages holding back our upgrade:
1)  [Morley](https://gitlab.com/morley-framework/morley/-/merge_requests/276)

PRs regarding this upgrade:
1) #362

**Comment by thealmarty** [comment]
I'd like to add the [`-Wunused-packages` flag](https://gitlab.haskell.org/ghc/ghc/commit/fe7e7e4a950a77326cc16f4ade30a67d20d7cdd5#8d11c404e91070407324f71df4a47224c0887148_105_105) when we've upgraded to 8.8.1, it warns about unused packages.

**Comment by mariari** [comment]
> I'd like to add the [`-Wunused-packages` flag](https://gitlab.haskell.org/ghc/ghc/commit/fe7e7e4a950a77326cc16f4ade30a67d20d7cdd5#8d11c404e91070407324f71df4a47224c0887148_105_105) when we've upgraded to 8.8.1, it warns about unused packages.

feel free to send a pr to #379 to get this up!

**Comment by thealmarty** [comment]
I will try out [Weeder](https://hackage.haskell.org/package/weeder) after the upgrade too. Turns out they added [a flag to generate HIE files](https://www.haskell.org/ghc/blog/20190626-HIEFiles.html) in 8.8.

**Comment by mariari** [comment]
Very nice, HIE generation will probably speed things up and maybe reduce the HIE ram usage

**Comment by thealmarty** [comment]
Done with #362 and #379 merged.
