### ISSUE TITLE
Simplifying the Frontend Parser

### ISSUE THREAD

**Issue by mariari** [cryptiumlabs/juvix#369]
Currently, a fair few type expressions are special cased in the parser

1) signatures require an arrow type.

2) arrow types are special.

I propose we remove both of these namely.

1) signatures get moved into taking an arbitrary expression 
    - This also mean that data types are the same!

2) Arrows are no longer specially parsed for, they are just infix functions.

3) we move many of the type only parts as part of the expression language, meaning refinements, etc are now expressions.

This creates the following ambi syntax issues

1) Punned records vs constraints.
     - I propose we do the following to fix it
        ```lisp
        { a } ;; constraint
        { a; } ;; record punned
        { a; b } ;; record 2 puns
         ```
    - This is a bit of a hack, but allows punned records to exist with the overlapping syntax of constraints.

**Comment by cwgoes** [comment]
> This also mean that data types are the same!

i.e., both signatures & definitions take `Term`s, and only the typechecker checks, right?

> Arrows are no longer specially parsed for, they are just infix functions.

I think this is a good idea. Have we considered how to allow for custom infix definition functions in the future, a bit like how it works in Agda perhaps (see [here](https://agda.readthedocs.io/en/v2.5.2/language/mixfix-operators.html))?

> we move many of the type only parts as part of the expression language, meaning refinements, etc are now expressions.

I think this probably also makes sense.

> Punned records vs constraints.

By punned records, do you mean row polymorphism? I don't quite understand the example, what is `{ a; }` defining - a type? a value? an update function?

**Comment by mariari** [comment]
```ocaml
type foo = {
  a : int
}

test a = { a }
```

This is valid OCaml.

It puns the creation of the record. I even use this idiom in some places in the juvix codebase IIRC, as it's very convinent to not say

```ocaml
test a = { a = a }
```

**Comment by cwgoes** [comment]
Ah I see. I think your hack works but I wonder if it is distinguishable enough visually.

Should we consider using a different sort of brackets for records & for constraints?

**Comment by mariari** [comment]
#366 covers all the changes outside of the punned record change.

**Comment by cwgoes** [comment]
Shall we close this issue then, or are there any remaining simplifications?

**Comment by mariari** [comment]
We can close the issue now
