### ISSUE TITLE
Upgrade CI memory

### ISSUE THREAD

**Issue by mariari** [cryptiumlabs/juvix#387]
With the current CI settings we run out of memory before our CI finishes

**Comment by cwgoes** [comment]
We should probably switch to Github Actions; I think it will end up being cheaper / faster.

**Comment by cwgoes** [comment]
Argh, apparently [our Docker file is too large](https://github.com/cryptiumlabs/juvix/runs/649395782?check_suite_focus=true).

**Comment by cwgoes** [comment]
Let's try https://github.com/cryptiumlabs/juvix/pull/391 first; if that doesn't do it we can pay for or switch CI.

**Comment by thealmarty** [comment]
I think we can close this?

**Comment by mariari** [comment]
We can close this for now, however we may have to re-open this in the future, when/if our build gets larger again
