### ISSUE TITLE
MVP core syntax & semantics

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#47]
Per the language reference, chapter 8.

For the first pass at the Juvix MVP, the syntax and type theory only need to include:
- Sorts
- Dependent function types
- Abstractions
- Applications
- Variables
- Type & usage annotations
- Primitive integer types, constants, and functions
- Self types (add these last, still finalizing & adding examples)

The MVP should be able to:
- Parse strings into terms / types of the core syntax
- Typecheck terms according to the typing rules in the language reference
- Erase terms to untyped lambda calculus programs according to the erasure rules in the language reference
- Pass untyped lambda calculus programs to the EAL inference engine & runtime

cc @thealmarty

**Comment by thealmarty** [comment]
I should probably read this at some point: http://tuprints.ulb.tu-darmstadt.de/9025/

**Comment by cwgoes** [comment]
Done.
