### ISSUE TITLE
Elegant language and logo

### ISSUE THREAD

**Issue by clarus** [cryptiumlabs/juvix#93]
I feel the Juvix logo is quite frightening for an "elegant language":

![image](https://user-images.githubusercontent.com/316665/64616491-f8af1380-d3dc-11e9-9442-b3915f623f08.png)

What about a horse like this one?
![image](https://user-images.githubusercontent.com/316665/64616599-2e53fc80-d3dd-11e9-9618-f9dac25d4716.png)

On a more general note, I am afraid by the pictures in your blog posts and thank you for the hard work on Juvix.

**Comment by clarus** [comment]
Duplicates https://github.com/cryptiumlabs/juvix/issues/57

**Comment by cwgoes** [comment]
The picture is of a [tardigrade](https://en.wikipedia.org/wiki/Tardigrade), micro-animals known for their resiliency and versatility across a wide range of environments - hence, perhaps, a suitable inspiration for a resilient language.

I would further argue that the various adaptations different tardigrade species have evolved are elegant in their adaptations to the environment, though perhaps the resulting phenotypes are not always aesthetically appealing to the human eye.

**Comment by cwgoes** [comment]
We're still looking for a kawaii tardigrade. Closing in favour of #57.
